### PR TITLE
fix cert scraping on newer Linkerd versions

### LINKED ISSUE #47: Failure to obtain certificates
There are some errors related to certificate scraping in the logs of the agent: 

```
error getting control plane certs: could not find _l5d_ns env var on proxy container [linkerd-proxy]"
```

This was caused by the fact that some env vars were removed from the proxy container in: https://github.com/linkerd/linkerd2/commit/aa9ee6b0078f7b3e5f24fe4341359066bdb503bc

### PR DESCRIPTION
**Pull request by zaharidichev**
The `_l5d_ns` and `_l5d_trustdomain` were recently removed from the
proxy definitions in Linkerd. This breaks cert scraping functionality. This PR
fixes that by instead relying on the `LINKERD2_PROXY_IDENTITY_LOCAL_NAME`
var whenever possible and filling in the svc account and namespace for the pod. 

To test: 

Ensure you run this agent on a cluster that have an older Linkerd version (stable-2.8.1).
Then run this agent with the latest edge. Ensure in both cases Linkerd certs are scraped
correctly. 

close #47

Signed-off-by: Zahari Dichev <zaharidichev@gmail.com>

### CODE REVIEW

File: agent/pkg/k8s/certificates.go [hunk 1]
```diff
@@ -80,13 +82,31 @@ func (c *Client) getControlPlaneComponentPod(component string) (*v1.Pod, error)
...
 			l5dtrustdomain = env.Value
 		}
+
+		if env.Name == linkerdProxyIdentityEnvVarName {
+			localName = env.Value
+		}
+	}
+
+	if l5dns == "" && l5dtrustdomain == "" {
+		// on newer versions of Linkerd these are not set, rely on the proxy local name for this
```
Comment (siggy) [inline agent/pkg/k8s/certificates.go:101]: can you describe a bit more in comments the difference between the linkerd versions? also, specify which version this changed?

something like...

old / `stable-2.8.1`:
```yaml
_l5d_ns: linkerd
_l5d_trustdomain: cluster.local
LINKERD2_PROXY_IDENTITY_LOCAL_NAME: $(_pod_sa).$(_pod_ns).serviceaccount.identity.$(_l5d_ns).$(_l5d_trustdomain)
```
new / `edge-22.2.2`:
```yaml
LINKERD2_PROXY_IDENTITY_LOCAL_NAME: $(_pod_sa).$(_pod_ns).serviceaccount.identity.linkerd.cluster.local
```

File: agent/pkg/k8s/certificates.go [hunk 2]
```diff
@@ -114,7 +135,7 @@ func (c *Client) extractRootsCerts(ctx context.Context, container *v1.Container,
 			cmName := ev.ValueFrom.ConfigMapKeyRef.Name
 			cm, err := c.k8sClient.CoreV1().ConfigMaps(namespace).Get(ctx, cmName, metav1.GetOptions{})
 			if err != nil {
-				return nil, fmt.Errorf("cannot obtain config map %s/%s", namespace, cmName)
+				return nil, fmt.Errorf("cannot obtain config map %s/%s: %s", namespace, cmName, err)
```
Comment (siggy) [inline agent/pkg/k8s/certificates.go:138]: can you use `%w`?

**Review by siggy — APPROVED** [review]
Nice! Left a couple minor comments, then 👍 🚢 

Confirmed this works with both `stable-2.8.1` and `edge-22.2.2`.
Screen Shot 2022-02-15 at 12 13 20 PM
